### ISSUE TITLE
Blue/black numbers in Fig. 9

### ISSUE THREAD

**Issue by drewkenjo** [drewkenjo/RICH-NIM-paper#13]
![image](https://user-images.githubusercontent.com/13206395/153526792-2a1ea42e-766e-43f0-a851-5c53bda4f7b5.png)

**Comment by andrsmit** [comment]
I updated the caption of Fig. 9 to mention what the blue numbers are, and I added more text to describe how the numbers were calculated.

**Comment by drewkenjo** [comment]
<img width=500 src=https://user-images.githubusercontent.com/13206395/153703166-be3007f8-c7ff-4e46-9fe2-8b3429c3d78c.png>
<img width=500 src=https://user-images.githubusercontent.com/13206395/153703129-d1f8eeba-7b24-4645-b828-3296621d973a.png>
