### ISSUE TITLE
stability of photon flux

### ISSUE THREAD

**Issue by drewkenjo** [drewkenjo/RICH-NIM-paper#16]
# Page 10
![image](https://user-images.githubusercontent.com/13206395/153526999-79cbb577-12b9-4c35-9df2-fbf2362b28b4.png)

**Comment by pdegtiarenko** [comment]
Added a sentence about it before Figure 24 on p.15

**Comment by drewkenjo** [comment]
![image](https://user-images.githubusercontent.com/13206395/153680056-11582cc9-36ba-4e6e-b191-35609d51ec48.png)
