### ISSUE TITLE
QE comparison with Hamamatsu

### ISSUE THREAD

**Issue by drewkenjo** [drewkenjo/RICH-NIM-paper#17]
# page 10
![image](https://user-images.githubusercontent.com/13206395/153527078-f6351647-3515-42c8-a73e-5d23d313aaf7.png)

**Comment by pdegtiarenko** [comment]
I have added a sentence at the end of the paragraph describing Fig. 24

**Comment by drewkenjo** [comment]
![image](https://user-images.githubusercontent.com/13206395/153680035-3ebabfbc-317c-41f3-8d1b-00dbc10eaeab.png)
