### ISSUE TITLE
Cross talk pictures need to be flipped

### ISSUE THREAD

**Issue by drewkenjo** [drewkenjo/RICH-NIM-paper#21]
<img width=400 src=https://user-images.githubusercontent.com/13206395/153527335-a152752d-5b81-4e6e-92c7-caed4fc6aa8b.png>
<img width=500 src=https://user-images.githubusercontent.com/13206395/153527359-d01d03b7-0ce4-4668-94bc-8d5c6b2776e2.png>

**Comment by drewkenjo** [comment]
# Picture flipped
![image](https://user-images.githubusercontent.com/13206395/153527732-ff3e5130-1f42-45f9-8e6f-1df17b5fc395.png)

**Comment by pdegtiarenko** [comment]
Looks good. The y axis labels need to be flipped in (d) plot

**Comment by drewkenjo** [comment]
![image](https://user-images.githubusercontent.com/13206395/153761341-3fb09a0a-42d6-4ba3-92ae-73738bf0103c.png)
