### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by drewkenjo** [drewkenjo/RICH-NIM-paper#8]
<table>
<tr><td width=400>
<img src=https://user-images.githubusercontent.com/13206395/153526072-59374d0a-815b-428b-9ce3-382b2b40722d.png>
</td></tr>
<tr><td width=400>
<img src=https://user-images.githubusercontent.com/13206395/153526092-2b76460d-b62d-4adf-b115-40e93995a175.png>
</td></tr>
<tr><td width=400>
<img src=https://user-images.githubusercontent.com/13206395/153526116-07488f5c-756b-4a6b-960d-37276f2420c1.png>
</td></tr>
</table>

**Comment by andrsmit** [comment]
I corrected the grammar in the sentence that previously had "unique", and slightly changed the second sentence in the caption for fig 5 (it was already changed, so I just made it read a little better).
